scrape_configs:
  - job_name: node_exporter
    scrape_interval: 1m
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 127.0.0.1:9100
    labels:
      instance: rpi2
  - job_name: simpleModbus
    scrape_interval: 1m
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 127.0.0.1:3000