# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  build_release:
      name: Generate cross-platform release
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.8'
  
      - name: Build for arm
        run: GOOS="linux" GOARCH="arm" go build

      - name: Gzip for arm
        run: tar -zcvf ./simpleModbus-linux-arm.tar.gz ./simpleModbus 

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./simpleModbus-linux-amd.tar.gz
          asset_name: simpleModbus-linux-amd.tar.gz
          asset_content_type: application/zip
